### ISSUE TITLE
Does regexp on response-blocklist-name works on any record type?

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#341] opened 2023-09-19 14:24 UTC
Should `response-blocklist-name` when using `regexp` hit anything in the answer, regarrdless record-type? Like HTTPS and SVCB records as well?

For example, I want to block an HTTPS record like below:
`blah.company.com. 120 IN HTTPS 1 . ipv4hint=\"1.2.3.4\" ipv6hint=\"1234:1:2:3::4\"`

By using an regexp like this (stupid/simple example):
`^ipv4hint`

It seems to work on `CNAME` and the more traditional records only?

**Comment by folbricht** [comment] 2023-09-20 07:13
It supports a subset of record types. You can see the list here https://github.com/folbricht/routedns/blob/master/response-blocklist-name.go#L77-L86

Should be easy to add something if necessary.

**Comment by cbuijs** [comment] 2023-09-20 11:09
Ah! Wait. I think we discussed this before :-).

I think it is probably okay and not a lot of work to at least the following record-types as well, where the last field in the answer is "text" and to be considered parseable (the other fields require more work I guess, but less relevant anyway):

`TXT`
`HTTPS`
`SVCB`

Not sure if the DNS Lib provide those fields as "text" as the `HTTPS` and `SVCB` normally seems to be encoded in some format. The `HTTPS` and `SVCB` ones are quite new, but the `HTTPS` is in use A **LOT** already.

**Comment by cbuijs** [comment] 2023-09-21 08:40
I had this issue before, and concatenate them with a space, which seems to be a common way of doing it.

**Comment by folbricht** [comment] 2023-09-21 08:43
Just updated it to join with whitespace

**Comment by cbuijs** [comment] 2023-10-18 09:29
Seems not to work. I didn't spend too much time on it. Looks like the `regexp` format I am using, isn't used somehow.

**Comment by cbuijs** [comment] 2023-10-18 09:47
I think (wild guess) is that `r.Target` is encoded in Base64 (decoding it would turn it into text), but I am not sure.

**Comment by folbricht** [comment] 2023-10-21 08:44
The issue is that "Target" is just the target string, i.e. just `.` in your example. The values are encoded separately. I pushed a change to encode the values like `. ipv4hint=1.2.3.4 ipv6hint=1234:1:2:3::4` without the quotes. So your regexp should work now.
Not sure if this is the right thing to do though, since it's no longer blocking based on "Target" only, but let's see how this works out first

**Comment by cbuijs** [comment] 2023-10-23 09:54
Not working still (using same example config above):
```
kdig one.one.one.one https
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 43692
;; Flags: qr rd ra ad; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; one.one.one.one.    		IN	HTTPS

;; ANSWER SECTION:
one.one.one.one.    	300	IN	HTTPS	1 . alpn=h3,h2 ipv4hint=1.1.1.1,1.0.0.1 ipv6hint=2606:4700:4700::1111,2606:4700:4700::1001

;; Received 121 B
;; Time 2023-10-23 11:51:52 CEST
;; From 192.168.1.32@53(UDP) in 27.2 ms
chris-eip-air:~ chrisbuijs$ kdig one.one.one.one https
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 21459
;; Flags: qr rd ra ad; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; one.one.one.one.    		IN	HTTPS

;; ANSWER SECTION:
one.one.one.one.    	287	IN	HTTPS	1 . alpn=h3,h2 ipv4hint=1.1.1.1,1.0.0.1 ipv6hint=2606:4700:4700::1111,2606:4700:4700::1001
```

**Comment by folbricht** [comment] 2023-10-28 06:43
Did you update from the branch before testing? I just tried it again and it seems to be working.

Logs
```
TRAC[0054] opening connection                            addr="1.1.1.1:853"
TRAC[0054] sending query                                 addr="1.1.1.1:853" qname=one.one.one.one.
DEBU[0054] blocking response                             client=127.0.0.1 id=cloudflare-blocklist qname=one.one.one.one. qtype=HTTPS rule="^.*ipv[46]hint.*$"
TRAC[0064] connection terminated by idle timeout         addr="1.1.1.1:853"
```

Config
```toml
[groups.cloudflare-blocklist]
type             = "response-blocklist-name"
resolvers        = ["cloudflare-dot"]
blocklist-format = "regexp"
blocklist= [
    '^.*ipv[46]hint.*$',
]
```

Output
```
$ dig -p 1153 @127.0.0.1 HTTPS one.one.one.one

; <<>> DiG 9.18.19 <<>> -p 1153 @127.0.0.1 HTTPS one.one.one.one
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 19249
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;one.one.one.one.		IN	HTTPS

;; Query time: 112 msec
;; SERVER: 127.0.0.1#1153(127.0.0.1) (UDP)
;; WHEN: Sat Oct 28 08:40:57 CEST 2023
;; MSG SIZE  rcvd: 33
```

**Comment by cbuijs** [comment] 2023-11-01 09:28
Cool. Will do a rebuild and test again in the next couple of days and let you know.

**Comment by cbuijs** [comment] 2023-11-01 09:35
Something I will be creating another ticket for but that just popped in my mind reading this all.

Would be cool that we can somehow use the existing block features by defining a regex where to match agains.

For example `response-ip` not only looking in `A` or/and `AAAA` records, but in parts of targets of other records too.

For example if we take the above example, and we want to match `1.1.1.1` as address, a matching/capturing regex could be given like this:

`^.*ipv[46]hint=(?P<IP>[^\s]+).*$`

The parentheses bit will be captured into `IP` that would be used to match against the list (using IP-Address here as example).

Hope this is clear.

**Comment by cbuijs** [comment] 2023-11-02 15:18
Just tested after rebuild and it works:
`msg="blocklist match, forwarding to blocklist-resolver" client=192.168.1.122 id=test qname=one.one.one.one. qtype=HTTPS resolver=noerror rule="^.*ipv[46]hint.*$"`

**Comment by folbricht** [comment] 2023-11-04 16:04
Thanks for checking it out. Merged

**Closed** 2023-11-06 07:58 UTC
